USE [master]
GO
/****** Object:  Database [Lab_3]    Script Date: 6/11/2018 9:48:03 AM ******/
CREATE DATABASE [Lab_3]
GO
ALTER DATABASE [Lab_3] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Lab_3].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Lab_3] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Lab_3] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Lab_3] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Lab_3] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Lab_3] SET ARITHABORT OFF 
GO
ALTER DATABASE [Lab_3] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Lab_3] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Lab_3] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Lab_3] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Lab_3] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Lab_3] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Lab_3] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Lab_3] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Lab_3] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Lab_3] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Lab_3] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Lab_3] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Lab_3] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Lab_3] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Lab_3] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Lab_3] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Lab_3] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Lab_3] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Lab_3] SET  MULTI_USER 
GO
ALTER DATABASE [Lab_3] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Lab_3] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Lab_3] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Lab_3] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [Lab_3] SET DELAYED_DURABILITY = DISABLED 
GO
USE [Lab_3]
GO
/****** Object:  Table [dbo].[tbl_Book]    Script Date: 6/11/2018 9:48:03 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tbl_Book](
	[BookCode] [int] IDENTITY(1,1) NOT NULL,
	[Title] [nchar](400) NOT NULL,
	[Author] [nchar](400) NOT NULL,
	[Publisher] [nchar](400) NOT NULL,
	[BookNumber] [int] NOT NULL,
 CONSTRAINT [PK_tbl_Book] PRIMARY KEY CLUSTERED 
(
	[BookCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[tbl_Copy]    Script Date: 6/11/2018 9:48:03 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tbl_Copy](
	[CopyCode] [int] IDENTITY(1,1) NOT NULL,
	[BookCode] [int] NOT NULL,
	[CopyNumber] [int] NOT NULL,
	[SequenceNumber] [int] NOT NULL,
	[Type] [nchar](10) NOT NULL,
	[Price] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CopyCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[tbl_Member]    Script Date: 6/11/2018 9:48:03 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tbl_Member](
	[MemberCode] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nchar](200) NULL,
	[Sex] [nchar](10) NULL,
	[Address] [nchar](200) NULL,
	[Telephone] [nchar](20) NULL,
	[Email] [nchar](100) NULL,
 CONSTRAINT [PK_tbl_Member] PRIMARY KEY CLUSTERED 
(
	[MemberCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[tbl_ReserveCopy]    Script Date: 6/11/2018 9:48:03 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tbl_ReserveCopy](
	[ReserveCopyCode] [int] IDENTITY(1,1) NOT NULL,
	[MemberCode] [int] NOT NULL,
	[CopyCode] [int] NOT NULL,
	[BorrowerNumber] [int] NOT NULL,
	[BorrowedDate] [date] NOT NULL,
	[DueDate] [date] NOT NULL,
	[ReturnDate] [date] NULL,
	[FeeAmount] [int] NOT NULL,
 CONSTRAINT [PK_tbl_Borrow] PRIMARY KEY CLUSTERED 
(
	[ReserveCopyCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[tbl_Copy]  WITH CHECK ADD  CONSTRAINT [FK_tbl_Copy_tbl_Book] FOREIGN KEY([BookCode])
REFERENCES [dbo].[tbl_Book] ([BookCode])
GO
ALTER TABLE [dbo].[tbl_Copy] CHECK CONSTRAINT [FK_tbl_Copy_tbl_Book]
GO
ALTER TABLE [dbo].[tbl_ReserveCopy]  WITH CHECK ADD  CONSTRAINT [FK_tbl_BorrowCopy_tbl_Copy] FOREIGN KEY([CopyCode])
REFERENCES [dbo].[tbl_Copy] ([CopyCode])
GO
ALTER TABLE [dbo].[tbl_ReserveCopy] CHECK CONSTRAINT [FK_tbl_BorrowCopy_tbl_Copy]
GO
ALTER TABLE [dbo].[tbl_ReserveCopy]  WITH CHECK ADD  CONSTRAINT [FK_tbl_BorrowCopy_tbl_Member] FOREIGN KEY([MemberCode])
REFERENCES [dbo].[tbl_Member] ([MemberCode])
GO
ALTER TABLE [dbo].[tbl_ReserveCopy] CHECK CONSTRAINT [FK_tbl_BorrowCopy_tbl_Member]
GO
USE [master]
GO
ALTER DATABASE [Lab_3] SET  READ_WRITE 
GO